### ISSUE TITLE
DandD crashing in exact mode

### ISSUE THREAD

**Issue by simolucaa** [jessicabonnie/dandd#9]
Hi,
we are trying to use your tool on some bacterial datasets. So far the dashing mode is working fine.

However, when launching DandD with the following command:
`./dandd tree --datadir ../../data/split_ecoli --tag ecoli --exact`
the tool seems to crash. Attached, you can also find the log file containing the errors. 

Any help is much appreciated.

[ecoli_exact.log](https://github.com/user-attachments/files/17718466/ecoli_exact.log)

**Comment by jessicabonnie** [comment]
Hi Marti,
It seems like KMC is struggling with at least one of the files and then choking on the incomplete output file when it tries to compute cardinality. So the kmc_pre  and kmc_suf files exist but they aren't usable. I recommend testing those files using kmc itself to identify which one complains. Something like this:

```
unique_names=$(ls ../../data/split_ecoli/*.kmc_* | sed 's/\.[^.]*$//' | sort | uniq)
for name in $unique_names; do
    echo "Processing $name"
    kmc "${name}" <SOME COMMAND>
done
```
After you have found it, just delete those two kmc files and try again!
